import rsnumpy as np
import rsplotlib.pyplot as plt

freq = np.linspace(1, 2, 101)
s11 = 0.1 * np.exp(1j * freq * np.pi)
s12 = 0.8 * np.exp(1j * freq * 2 * np.pi)

fig, axs = plt.subplots(2, 1, figsize=(8, 6))
axs[0].plot(freq, 20 * np.log10(np.abs(s11)), label='S11')
axs[0].set_title('Subplot 1')
axs[1].plot(freq, 20 * np.log10(np.abs(s12)), label='S12')
axs[1].set_title('Subplot 2')
fig.suptitle("Ideal 50-Ohm balun", pad=5)
plt.savefig("./test/test_rf/suptitle_follow_default.png")
plt.clf()
print("Saved suptitle_follow_default.png (default layout)")

fig, axs = plt.subplots(2, 1, figsize=(8, 6))
axs[0].plot(freq, 20 * np.log10(np.abs(s11)), label='S11')
axs[0].set_title('Subplot 1')
axs[1].plot(freq, 20 * np.log10(np.abs(s12)), label='S12')
axs[1].set_title('Subplot 2')
fig.suptitle("Ideal 50-Ohm balun", pad=5)
plt.subplots_adjust(top=0.8)
plt.savefig("./test/test_rf/suptitle_follow_top8.png")
plt.clf()
print("Saved suptitle_follow_top8.png (top=0.8)")

fig, axs = plt.subplots(2, 1, figsize=(8, 6))
axs[0].plot(freq, 20 * np.log10(np.abs(s11)), label='S11')
axs[0].set_title('Subplot 1')
axs[1].plot(freq, 20 * np.log10(np.abs(s12)), label='S12')
axs[1].set_title('Subplot 2')
fig.suptitle("Ideal 50-Ohm balun", pad=5)
plt.subplots_adjust(top=0.6)
plt.savefig("./test/test_rf/suptitle_follow_top6.png")
plt.clf()
print("Saved suptitle_follow_top6.png (top=0.6)")

fig, axs = plt.subplots(2, 1, figsize=(8, 6))
axs[0].plot(freq, 20 * np.log10(np.abs(s11)), label='S11')
axs[0].set_title('Subplot 1')
axs[1].plot(freq, 20 * np.log10(np.abs(s12)), label='S12')
axs[1].set_title('Subplot 2')
fig.suptitle("Ideal 50-Ohm balun", pad=0)
plt.subplots_adjust(top=0.8)
plt.savefig("./test/test_rf/suptitle_follow_pad0_top8.png")
plt.clf()
print("Saved suptitle_follow_pad0_top8.png (pad=0, top=0.8)")

fig, axs = plt.subplots(2, 1, figsize=(8, 6))
axs[0].plot(freq, 20 * np.log10(np.abs(s11)), label='S11')
axs[0].set_title('Subplot 1')
axs[1].plot(freq, 20 * np.log10(np.abs(s12)), label='S12')
axs[1].set_title('Subplot 2')
fig.suptitle("Ideal 50-Ohm balun", pad=10)
plt.subplots_adjust(top=0.8)
plt.savefig("./test/test_rf/suptitle_follow_pad10_top8.png")
plt.clf()
print("Saved suptitle_follow_pad10_top8.png (pad=10, top=0.8)")

print("\nAll suptitle follow tests completed!")