use crate::colors::RgbColor;

#[derive(Clone)]
#[allow(dead_code)]
pub enum PlotElement {
    Line {
        x: Vec<Option<f64>>,
        y: Vec<Option<f64>>,
        label: Option<String>,
        color: String,
        linestyle: String,
        marker: Option<String>,
        linewidth: f64,
        color_idx: usize,
        solid_capstyle: String,
        markersize: Option<f64>,
    },
    Scatter {
        x: Vec<f64>,
        y: Vec<f64>,
        s: f64,
        c: String,
        marker: String,
        label: Option<String>,
        alpha: f64,
        color_idx: usize,
    },
    ScatterMulti {
        x: Vec<f64>,
        y: Vec<f64>,
        s_list: Option<Vec<f64>>,
        c_list: Option<Vec<String>>,
        marker: String,
        label: Option<String>,
        alpha: f64,
        color_idx: usize,
    },
    Bar {
        x: Vec<f64>,
        height: Vec<f64>,
        width: f64,
        color: String,
        label: Option<String>,
        color_idx: usize,
    },
    BarH {
        y: Vec<f64>,
        width: Vec<f64>,
        height: f64,
        color: String,
        label: Option<String>,
        color_idx: usize,
    },
    Hist {
        data_all: Vec<Vec<f64>>,
        bins: usize,
        density: bool,
        histtype: String,
        label: Option<String>,
        alpha: f64,
        colors: Vec<String>,
        color_idx: usize,
        bin_edges: Option<Vec<f64>>,
    },
    Image {
        data: Vec<Vec<f64>>,
        cmap: String,
    },
    Text {
        x: f64,
        y: f64,
        text: String,
        fontsize: i32,
        color: RgbColor,
        font_family: Option<String>,
    },
    HLine {
        y: f64,
        color: String,
        linestyle: String,
        linewidth: f64,
        color_idx: usize,
    },
    VLine {
        x: f64,
        color: String,
        linestyle: String,
        linewidth: f64,
        color_idx: usize,
    },
    Pie {
        x: Vec<f64>,
        labels: Option<Vec<String>>,
        colors: Option<Vec<String>>,
        autopct: Option<String>,
        startangle: f64,
    },
    FillBetween {
        x: Vec<f64>,
        y1: Vec<f64>,
        y2: Vec<f64>,
        color: String,
        alpha: f64,
        label: Option<String>,
    },
    ErrorBar {
        x: Vec<f64>,
        y: Vec<f64>,
        yerr: Option<Vec<f64>>,
        xerr: Option<Vec<f64>>,
        fmt: String,
        color: String,
        label: Option<String>,
        capsize: f64,
    },
    Stem {
        x: Vec<f64>,
        y: Vec<f64>,
        linefmt: String,
        markerfmt: String,
        label: Option<String>,
    },
    Step {
        x: Vec<f64>,
        y: Vec<f64>,
        where_: String,
        label: Option<String>,
        color: String,
        linestyle: String,
        linewidth: f64,
    },
    BoxPlot {
        data: Vec<Vec<f64>>,
        labels: Option<Vec<String>>,
        vert: bool,
    },
    Annotate {
        text: String,
        xy: (f64, f64),
        xytext: Option<(f64, f64)>,
        fontsize: f64,
        color: String,
    },
    Stack {
        x: Vec<f64>,
        y_series: Vec<Vec<f64>>,
        labels: Option<Vec<String>>,
        colors: Option<Vec<String>>,
        alpha: f64,
    },
    HSpan {
        y1: f64,
        y2: f64,
        color: String,
        alpha: f64,
    },
    VSpan {
        x1: f64,
        x2: f64,
        color: String,
        alpha: f64,
    },
    AxLine {
        xy1: (f64, f64),
        xy2: (f64, f64),
        color: String,
        linestyle: String,
        linewidth: f64,
    },
    Arrow {
        x1: f64,
        y1: f64,
        x2: f64,
        y2: f64,
        color: String,
        linewidth: f64,
        head_size: f64,
    },
}
